### ISSUE TITLE
Features configuration override

### ISSUE THREAD

**Issue by jdecool** [novaway/NovawayFeatureFlagBundle#10]
Content of `config.yml` :

```yaml
# ...
novaway_feature_flag
    features:
        feature1: false
        feature2: true
        feature3: false
        feature4: true
        feature5: false
        feature6: true
        feature7: false
```

Override configurations in `config_prod.yml` :

```yaml
novaway_feature_flag:
    features:
        feature7: true
```

Dump of the features configuration in PHP :

```php
// ...
‘feature7’ => array(
    ‘enabled’ => false,
),
0 => array(
    ‘enabled’ => true,
),
```
